name: CI

on:
  pull_request:
    paths-ignore:
    - '**.md'
    - '**.py'
    - '**.png'
    - '**.gif'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - 25.3
          - 26.3
          - 27.2
    steps:
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}

    - uses: actions/checkout@v2
    - name: Run tests
      run: 'make test'
